import {
  LeftOutlined,
  RightOutlined,
  DownOutlined,
  UpOutlined,
  CopyOutlined,
  DeleteOutlined,
  ApiOutlined,
  PlusSquareOutlined,
  MinusSquareOutlined,
  PlusOutlined,
  MinusOutlined,
  ApartmentOutlined,
  AppstoreAddOutlined,
  ClusterOutlined,
  QuestionCircleOutlined,
  CodeOutlined,
} from '@ant-design/icons'

export {
  LeftOutlined,
  RightOutlined,
  DownOutlined,
  UpOutlined,
  CopyOutlined,
  DeleteOutlined,
  ApiOutlined,
  PlusSquareOutlined,
  MinusSquareOutlined,
  PlusOutlined,
  MinusOutlined,
  ApartmentOutlined,
  AppstoreAddOutlined,
  ClusterOutlined,
  QuestionCircleOutlined,
  CodeOutlined,
}
